# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 04:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name=b'Date')),
                ('stock_in', models.IntegerField()),
                ('stock_out', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('particulars', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name=b'Date')),
                ('shipment_provider', models.CharField(choices=[(b'LBC', b'LBC'), (b'GO', b'GO'), (b'JRS Express', b'JRS Express'), (b'Zen', b'Zen'), (b'Philpost', b'Philpost'), (b'EMS', b'EMS'), (b'Fedex', b'Fedex'), (b'DHL', b'DHL')], max_length=100)),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('address', models.TextField(max_length=250)),
                ('barangay', models.CharField(max_length=250)),
                ('city_and_municipality', models.CharField(max_length=250)),
                ('zip_code', models.CharField(max_length=4)),
                ('province', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=13)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[(b'On going', b'On going'), (b'Shipping', b'Shipping'), (b'On hold', b'On hold')], default=b'On going', max_length=100)),
                ('special_instructions', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Product'),
        ),
    ]
