# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('shipment_provider', models.CharField(max_length=250)),
                ('name_of_recipient', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('barangay', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=13)),
                ('order', models.CharField(max_length=250)),
            ],
        ),
    ]
