# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_order_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='remarks',
        ),
    ]
