# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_remove_order_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.CharField(default='', max_length=250),
        ),
    ]
