# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_auto_20171121_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'On going', b'On going'), (b'Shipping', b'Shipping'), (b'On hold', b'On hold'), (b'Delivered', b'Delivered')], default=b'On going', max_length=100),
        ),
    ]
