# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_order_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('particulars', models.CharField(max_length=250)),
                ('in_algicleanz', models.CharField(max_length=250)),
                ('out_algicleanz', models.CharField(max_length=250)),
                ('balance_algicleanz', models.CharField(max_length=250)),
                ('in_amfit', models.CharField(max_length=250)),
                ('out_amfit', models.CharField(max_length=250)),
                ('balance_amfit', models.CharField(max_length=250)),
            ],
        ),
    ]
