# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0010_auto_20170716_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_logo',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
