# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0013_auto_20170717_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='remarks',
            new_name='special_instructions',
        ),
    ]
