# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0014_auto_20170717_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_logo',
            field=models.ImageField(blank=True, upload_to='product_image'),
        ),
    ]
