# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0019_auto_20170723_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 25, 4, 38, 12, 149053), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 25, 4, 38, 12, 148050), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(choices=[('Amfit Coffee', 'Amfit Coffee'), ('Algi Cleans', 'Algi Cleans')], max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=6),
        ),
    ]
