# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0022_auto_20170725_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(default=0, max_length=7),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='balance',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 11, 16, 16, 1, 496608), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_in',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_out',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 11, 16, 16, 1, 494102), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_provider',
            field=models.CharField(choices=[('LBC', 'LBC'), ('GO', 'GO'), ('JRS Express', 'JRS Express'), ('Zen', 'Zen'), ('Philpost', 'Philpost')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.UserProfile'),
        ),
    ]
