# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0023_auto_20170811_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 11, 18, 7, 56, 937471), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 11, 18, 7, 56, 934484), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
