# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0028_auto_20170906_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 6, 23, 40, 28, 550829), verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_out',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 6, 23, 40, 28, 551464), verbose_name=b'Date'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ordering.Product'),
            preserve_default=False,
        ),
    ]
