# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0029_auto_20170906_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 6, 23, 44, 21, 197756), verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 6, 23, 44, 21, 198387), verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Product'),
        ),
    ]
