# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0030_auto_20170906_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 7, 1, 1, 19, 36910), verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 7, 1, 1, 19, 37541), verbose_name=b'Date'),
        ),
    ]
