# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 18:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0031_auto_20170907_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 10, 2, 12, 25, 196971), verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 10, 2, 12, 25, 197589), verbose_name=b'Date'),
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='ordering.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
