# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 19:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0032_auto_20170910_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='address',
            field=models.TextField(default='address', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='barangay',
            field=models.CharField(default='brgy', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='city_and_municipality',
            field=models.CharField(default='city and municipality', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='first_name',
            field=models.CharField(default='first name', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='last_name',
            field=models.CharField(default='last name', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='middle_name',
            field=models.CharField(default='middle name', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='phone',
            field=models.CharField(default='phone', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='province',
            field=models.CharField(default='province', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='shipment_provider',
            field=models.CharField(default='shipment provider', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='special_instructions',
            field=models.CharField(default=b'', max_length=250),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 10, 2, 59, 27, 280965), verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 10, 2, 59, 27, 281591), verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Product'),
        ),
    ]
