# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0034_auto_20171029_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'On going', b'On going'), (b'Shipping', b'Shipping'), (b'On hold', b'On hold')], default=b'On going', max_length=100),
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
