# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0035_auto_20171030_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product_logo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
