# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0037_auto_20171111_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.CharField(default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
