# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0038_auto_20171111_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(max_length=4),
        ),
    ]
