# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0039_auto_20171112_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=4),
        ),
    ]
