# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0041_auto_20171115_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Product'),
        ),
    ]
